apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store
spec:
  provider:
    azurekv:
      # TENANT_ID and KEY_VAULT_URI are replaced by the aks-bootstrap workflow
      tenantId: TENANT_ID
      vaultUrl: KEY_VAULT_URI
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
