apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: example-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: example-key
      remoteRef:
        key: example-secret
